[book]
authors = ["z0gSh1u"]
language = "en"         # 翻译为了中文，但 HTML lang="en" 先保持不变
src = "main"
title = "用 Claude 构建应用"

[output.html]
git-repository-url = "https://github.com/z0gSh1u/build-with-claude"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/z0gSh1u/build-with-claude/edit/master/main/{path}"
